Repository hudson-and-thames/mlfinlab, pull requests merged in 2019-09, with the labels that each got.

#125 Docs bet sizing
  docs/source/conf.py
  docs/source/implementations/bet_sizing.rst
  docs/source/implementations/bet_sizing_images/bet_sizing.png
  docs/source/implementations/bet_sizing_images/ef3m.png
  docs/source/index.rst
  mlfinlab/__init__.py
  mlfinlab/bet_sizing/__init__.py
  mlfinlab/bet_sizing/bet_sizing.py
  mlfinlab/bet_sizing/ch10_snippets.py
  mlfinlab/bet_sizing/ef3m.py
Labels: Documentation

#119 Feature importance
  docs/source/implementations/feature_imp_images/mda_feat_imp.png
  docs/source/implementations/feature_imp_images/mdi_feat_imp.png
  docs/source/implementations/feature_imp_images/pca_correlation_analysis.png
  docs/source/implementations/feature_imp_images/sfi_feat_imp.png
  docs/source/implementations/feature_importance.rst
  docs/source/index.rst
  mlfinlab/__init__.py
  mlfinlab/ensemble/__init__.py
  mlfinlab/feature_importance/__init__.py
  mlfinlab/feature_importance/importance.py
  mlfinlab/feature_importance/orthogonal.py
  mlfinlab/tests/test_feature_importance.py
  requirements.txt
Labels: enhancement

#126 Bug fix: Triple barrier
  mlfinlab/labeling/labeling.py
  mlfinlab/tests/test_labels.py
Labels: bug

#105 Add Portfolio Optimisation Module
  .coveragerc
  .gitignore
  README.md
  docs/source/implementations/portfolio_optimisation.rst
  docs/source/index.rst
  mlfinlab/features/fracdiff.py
  mlfinlab/portfolio_optimization/__init__.py
  mlfinlab/portfolio_optimization/cla.py
  mlfinlab/portfolio_optimization/hrp.py
  mlfinlab/portfolio_optimization/mean_variance.py
  mlfinlab/tests/test_data/stock_prices.csv
  mlfinlab/tests/test_portfolio_optimisation.py
  requirements.txt
Labels: enhancement

#129 Develop
  .coveragerc
  .gitignore
  README.md
  docs/source/_static/.gitkeep
  docs/source/conf.py
  docs/source/implementations/bet_sizing.rst
  docs/source/implementations/bet_sizing_images/bet_sizing.png
  docs/source/implementations/bet_sizing_images/ef3m.png
  docs/source/implementations/cross_validation.rst
  docs/source/implementations/cross_validation_images/embargo.png
  docs/source/implementations/cross_validation_images/purging.png
  docs/source/implementations/feature_imp_images/mda_feat_imp.png
  docs/source/implementations/feature_imp_images/mdi_feat_imp.png
  docs/source/implementations/feature_imp_images/pca_correlation_analysis.png
  docs/source/implementations/feature_imp_images/sfi_feat_imp.png
  docs/source/implementations/feature_importance.rst
  docs/source/implementations/filters.rst
  docs/source/implementations/labeling.rst
  docs/source/implementations/portfolio_optimisation.rst
  docs/source/implementations/sampling.rst
  docs/source/implementations/sb_bagging.rst
  docs/source/index.rst
  mlfinlab/__init__.py
  mlfinlab/bet_sizing/README.md
  mlfinlab/bet_sizing/__init__.py
  mlfinlab/bet_sizing/bet_sizing.py
  mlfinlab/bet_sizing/ch10_snippets.py
  mlfinlab/bet_sizing/ef3m.py
  mlfinlab/cross_validation/__init__.py
  mlfinlab/cross_validation/cross_validation.py
  mlfinlab/ensemble/__init__.py
  mlfinlab/ensemble/sb_bagging.py
  mlfinlab/feature_importance/__init__.py
  mlfinlab/feature_importance/importance.py
  mlfinlab/feature_importance/orthogonal.py
  mlfinlab/features/fracdiff.py
  mlfinlab/filters/filters.py
  mlfinlab/labeling/labeling.py
  mlfinlab/portfolio_optimization/__init__.py
  mlfinlab/portfolio_optimization/cla.py
  mlfinlab/portfolio_optimization/hrp.py
  mlfinlab/portfolio_optimization/mean_variance.py
  mlfinlab/sampling/bootstrapping.py
  mlfinlab/tests/test_bet_sizing.py
  mlfinlab/tests/test_ch10_snippets.py
  mlfinlab/tests/test_cross_validation.py
  mlfinlab/tests/test_data/stock_prices.csv
  mlfinlab/tests/test_ef3m.py
  mlfinlab/tests/test_feature_importance.py
  mlfinlab/tests/test_filters.py
  mlfinlab/tests/test_labels.py
  mlfinlab/tests/test_portfolio_optimisation.py
  mlfinlab/tests/test_sampling.py
  mlfinlab/tests/test_sb_bagging.py
  requirements.txt
  scripts/run_tests.py
Labels: enhancement

#136 Bugfix betsize budget div zero
  mlfinlab/bet_sizing/bet_sizing.py
  mlfinlab/tests/test_bet_sizing.py
Labels: bug
