Repository hudson-and-thames/mlfinlab, pull requests merged in 2020-03, with the labels that each got.

#208 Delete dependencies
  CONTRIBUTING.md
  README.md
  requirements.txt
  setup.cfg
Labels: enhancement

#209 Fix docs
  docs/source/implementations/microstructural_features.rst
Labels: Documentation

#214 Chapter 14: Backtest statistics
  docs/source/implementations/backtest_statistics.rst
  docs/source/index.rst
  mlfinlab/backtest_statistics/__init__.py
  mlfinlab/backtest_statistics/statistics.py
  mlfinlab/tests/test_backtest_statistics.py
Labels: enhancement

#217 Sponsor popup
  README.md
  docs/source/index.rst
  mlfinlab/__init__.py
Labels: enhancement

#210 [Ready-to-Merge] Implement the HCAA Algorithm
  docs/source/implementations/portfolio_optimisation.rst
  mlfinlab/portfolio_optimization/cla.py
  mlfinlab/portfolio_optimization/hcaa.py
  mlfinlab/portfolio_optimization/hrp.py
  mlfinlab/portfolio_optimization/mean_variance.py
  mlfinlab/portfolio_optimization/returns_estimators.py
  mlfinlab/portfolio_optimization/risk_metrics.py
  mlfinlab/tests/test_cla.py
  mlfinlab/tests/test_hcaa.py
  mlfinlab/tests/test_hrp.py
  mlfinlab/tests/test_mean_variance.py
  mlfinlab/tests/test_portfolio_optimisation.py
  mlfinlab/tests/test_risk_metrics.py
Labels: enhancement

#220 Add docstrings for expected returns
  mlfinlab/portfolio_optimization/cla.py
  mlfinlab/portfolio_optimization/hcaa.py
  mlfinlab/portfolio_optimization/hrp.py
  mlfinlab/portfolio_optimization/mean_variance.py
  mlfinlab/portfolio_optimization/returns_estimators.py
  mlfinlab/portfolio_optimization/risk_metrics.py
Labels: Documentation

#222 A minor change that makes get_events usable with a new version of pandas (and old)
  docs/source/conf.py
  mlfinlab/__init__.py
  setup.cfg
Labels: bug

#224 Some bug fixes
  mlfinlab/portfolio_optimization/hrp.py
  mlfinlab/portfolio_optimization/mean_variance.py
Labels: bug

#229 Backtest Statistics Update
  docs/source/conf.py
  docs/source/implementations/backtest_statistics.rst
  mlfinlab/__init__.py
  mlfinlab/backtest_statistics/__init__.py
  mlfinlab/backtest_statistics/statistics.py
  mlfinlab/tests/test_backtest_statistics.py
  setup.cfg
Labels: enhancement

#230 Add options for specifying linkage in HCAA
  mlfinlab/portfolio_optimization/__init__.py
  mlfinlab/portfolio_optimization/cla.py
  mlfinlab/portfolio_optimization/hcaa.py
  mlfinlab/tests/test_hcaa.py
Labels: enhancement

#231 T1 values micro
  mlfinlab/microstructural_features/feature_generator.py
  mlfinlab/microstructural_features/second_generation.py
  mlfinlab/tests/test_microstructural_features.py
Labels: enhancement

#236 Update documentation:
  docs/source/implementations/portfolio_optimisation.rst
Labels: Documentation

#237 Tail Set Labels
  .coveragerc
  docs/source/implementations/labeling_images/performance_tail_sets.png
  docs/source/implementations/labeling_images/tail_sets_perf.png
  docs/source/implementations/labeling_images/var_distribution.png
  docs/source/implementations/labeling_tail_sets.rst
  docs/source/implementations/tb_meta_labeling.rst
  docs/source/index.rst
  mlfinlab/__init__.py
  mlfinlab/labeling/__init__.py
  mlfinlab/labeling/tail_sets.py
Labels: enhancement

#223 Change pandas loc with reindex to make function useable with pandas 1.0.
  mlfinlab/labeling/labeling.py
Labels: enhancement

#235 Campbell R. Harvey and Yan Liu "Backtesting" module
  docs/source/implementations/backtesting.rst
  docs/source/index.rst
  mlfinlab/__init__.py
  mlfinlab/backtest_statistics/__init__.py
  mlfinlab/backtest_statistics/backtests.py
  mlfinlab/backtest_statistics/statistics.py
  mlfinlab/tests/test_backtest_statistics.py
  mlfinlab/tests/test_backtests.py
Labels: Documentation, enhancement
