Repository hudson-and-thames/mlfinlab, pull requests merged in 2020-05, with the labels that each got.

#297 Update readme
  CONTRIBUTING.md
  README.md
  docs/source/index.rst
  docs/source/logo/HnT.png
  docs/source/logo/Slack.png
  docs/source/logo/journals.png
  mlfinlab/__init__.py
  setup.cfg
Labels: Documentation

#294 Docs upgrade
  docs/source/implementations/backtesting.rst
  docs/source/implementations/clustering_images/onc_base_clustering.png
  docs/source/implementations/clustering_images/onc_higher_level.png
  docs/source/implementations/codependence.rst
  docs/source/implementations/frac_diff.rst
  docs/source/implementations/onc.rst
  docs/source/implementations/structural_breaks.rst
  docs/source/portfolio_optimisation/critical_line_algorithm.rst
  docs/source/portfolio_optimisation/mean_variance.rst
  docs/source/portfolio_optimisation/nested_clustered_optimisation.rst
  docs/source/portfolio_optimisation/portfolio_optimisation_images/var_cvar_concepts.png
  docs/source/portfolio_optimisation/returns_estimation.rst
  docs/source/portfolio_optimisation/risk_estimators.rst
  docs/source/portfolio_optimisation/risk_metrics.rst
  docs/source/portfolio_optimisation/theory_implied_correlation.rst
  mlfinlab/portfolio_optimization/nco.py
  mlfinlab/portfolio_optimization/returns_estimators.py
  mlfinlab/portfolio_optimization/risk_estimators.py
  mlfinlab/portfolio_optimization/risk_metrics.py
  mlfinlab/portfolio_optimization/tic.py
  mlfinlab/tests/test_risk_estimators.py
Labels: Documentation

#281 Datasets
  docs/source/getting_started/datasets.rst
  docs/source/index.rst
  mlfinlab/__init__.py
  mlfinlab/datasets/__init__.py
  mlfinlab/datasets/data/dollar_bar_sample.csv
  mlfinlab/datasets/data/stock_prices.csv
  mlfinlab/datasets/data/tick_data.csv
  mlfinlab/datasets/load_datasets.py
  mlfinlab/tests/test_datasets.py
Labels: Documentation, enhancement

#272 CFI, Feature Clustering and Codependence Matrix
  docs/source/implementations/codependence.rst
  docs/source/implementations/feature_clusters.rst
  docs/source/implementations/feature_imp_images/clustered_mda.png
  docs/source/implementations/feature_imp_images/clustered_mdi.png
  docs/source/implementations/feature_importance.rst
  docs/source/index.rst
  mlfinlab/clustering/__init__.py
  mlfinlab/clustering/feature_clusters.py
  mlfinlab/clustering/onc.py
  mlfinlab/codependence/__init__.py
  mlfinlab/codependence/codependence_matrix.py
  mlfinlab/feature_importance/importance.py
  mlfinlab/tests/test_codependence.py
  mlfinlab/tests/test_feature_clusters.py
  mlfinlab/tests/test_feature_importance.py
  mlfinlab/util/__init__.py
  mlfinlab/util/generate_dataset.py
  requirements.txt
  setup.cfg
Labels: Documentation, enhancement

#291 Fix smt structural breaks
  docs/source/implementations/structural_breaks.rst
  mlfinlab/structural_breaks/sadf.py
  mlfinlab/tests/test_backtests.py
  mlfinlab/tests/test_structural_breaks.py
Labels: bug, enhancement

#293 Universal Portfolio
  mlfinlab/online_portfolio_selection/__init__.py
  mlfinlab/online_portfolio_selection/benchmarks/__init__.py
  mlfinlab/online_portfolio_selection/benchmarks/best_constant_rebalanced_portfolio.py
  mlfinlab/online_portfolio_selection/benchmarks/best_stock.py
  mlfinlab/online_portfolio_selection/benchmarks/buy_and_hold.py
  mlfinlab/online_portfolio_selection/benchmarks/constant_rebalanced_portfolio.py
  mlfinlab/online_portfolio_selection/momentum/__init__.py
  mlfinlab/online_portfolio_selection/momentum/exponential_gradient.py
  mlfinlab/online_portfolio_selection/momentum/follow_the_leader.py
  mlfinlab/online_portfolio_selection/momentum/follow_the_regularized_leader.py
  mlfinlab/online_portfolio_selection/online_portfolio_selection.py
  mlfinlab/online_portfolio_selection/universal_portfolio.py
  mlfinlab/tests/test_online_portfolio_selection.py
  mlfinlab/tests/test_universal_portfolio.py
Labels: enhancement

#312 Mean reversion
  .gitignore
  mlfinlab/online_portfolio_selection/__init__.py
  mlfinlab/online_portfolio_selection/mean_reversion/confidence_weighted_mean_reversion.py
  mlfinlab/online_portfolio_selection/mean_reversion/online_moving_average_reversion.py
  mlfinlab/online_portfolio_selection/mean_reversion/passive_aggressive_mean_reversion.py
  mlfinlab/online_portfolio_selection/mean_reversion/robust_median_reversion.py
  mlfinlab/online_portfolio_selection/universal_portfolio.py
  mlfinlab/tests/test_confidence_weighted_mean_reversion.py
  mlfinlab/tests/test_online_moving_average_reversion.py
  mlfinlab/tests/test_passive_aggressive_mean_reversion.py
  mlfinlab/tests/test_robust_median_reversion.py
Labels: enhancement

#310 Docstrings same style
  docs/source/implementations/frac_diff.rst
  docs/source/implementations/onc.rst
  docs/source/implementations/sampling.rst
  docs/source/portfolio_optimisation/hierarchical_risk_parity.rst
  docs/source/portfolio_optimisation/mean_variance.rst
  mlfinlab/backtest_statistics/statistics.py
  mlfinlab/clustering/feature_clusters.py
  mlfinlab/clustering/onc.py
  mlfinlab/codependence/codependence_matrix.py
  mlfinlab/codependence/correlation.py
  mlfinlab/codependence/information.py
  mlfinlab/cross_validation/combinatorial.py
  mlfinlab/cross_validation/cross_validation.py
  mlfinlab/data_structures/base_bars.py
  mlfinlab/data_structures/imbalance_data_structures.py
  mlfinlab/data_structures/run_data_structures.py
  mlfinlab/data_structures/standard_data_structures.py
  mlfinlab/data_structures/time_data_structures.py
  mlfinlab/ensemble/sb_bagging.py
  mlfinlab/feature_importance/fingerpint.py
  mlfinlab/feature_importance/importance.py
  mlfinlab/feature_importance/orthogonal.py
  mlfinlab/features/fracdiff.py
  mlfinlab/filters/filters.py
  mlfinlab/labeling/labeling.py
  mlfinlab/labeling/tail_sets.py
  mlfinlab/labeling/trend_scanning.py
  mlfinlab/microstructural_features/encoding.py
  mlfinlab/microstructural_features/entropy.py
  mlfinlab/microstructural_features/feature_generator.py
  mlfinlab/microstructural_features/first_generation.py
  mlfinlab/microstructural_features/misc.py
  mlfinlab/microstructural_features/second_generation.py
  mlfinlab/microstructural_features/third_generation.py
  mlfinlab/portfolio_optimization/cla.py
  mlfinlab/portfolio_optimization/hcaa.py
  mlfinlab/portfolio_optimization/hrp.py
  mlfinlab/portfolio_optimization/mean_variance.py
  mlfinlab/portfolio_optimization/nco.py
  mlfinlab/portfolio_optimization/returns_estimators.py
  mlfinlab/portfolio_optimization/risk_estimators.py
  mlfinlab/sample_weights/attribution.py
  mlfinlab/sampling/bootstrapping.py
  mlfinlab/sampling/concurrent.py
  mlfinlab/structural_breaks/chow.py
  mlfinlab/structural_breaks/cusum.py
  mlfinlab/structural_breaks/sadf.py
  mlfinlab/tests/test_hrp.py
  mlfinlab/util/generate_dataset.py
  mlfinlab/util/misc.py
  mlfinlab/util/multiprocess.py
  mlfinlab/util/volatility.py
  mlfinlab/util/volume_classifier.py
Labels: Documentation

#317 Correlation Driven Nonparametric Learning
  .gitignore
  mlfinlab/online_portfolio_selection/__init__.py
  mlfinlab/online_portfolio_selection/mean_reversion/__init__.py
  mlfinlab/online_portfolio_selection/online_portfolio_selection.py
  mlfinlab/online_portfolio_selection/pattern_matching/__init__.py
  mlfinlab/online_portfolio_selection/pattern_matching/correlation_driven_nonparametric_learning.py
  mlfinlab/online_portfolio_selection/pattern_matching/correlation_driven_nonparametric_learning_k.py
  mlfinlab/online_portfolio_selection/pattern_matching/correlation_driven_nonparametric_learning_uniform.py
  mlfinlab/online_portfolio_selection/pattern_matching/functional_correlation_driven_nonparametric_learning.py
  mlfinlab/online_portfolio_selection/pattern_matching/functional_correlation_driven_nonparametric_learning_k.py
  mlfinlab/online_portfolio_selection/pattern_matching/symmetric_correlation_driven_nonparametric_learning.py
  mlfinlab/online_portfolio_selection/pattern_matching/symmetric_correlation_driven_nonparametric_learning_k.py
  mlfinlab/online_portfolio_selection/universal_portfolio.py
  mlfinlab/tests/test_correlation_driven_nonparametric_learning.py
  mlfinlab/tests/test_correlation_driven_nonparametric_learning_k.py
  mlfinlab/tests/test_correlation_driven_nonparametric_learning_uniform.py
  mlfinlab/tests/test_functional_correlation_driven_nonparametric_learning.py
  mlfinlab/tests/test_functional_correlation_driven_nonparametric_learning_k.py
  mlfinlab/tests/test_symmetric_correlation_driven_nonparametric_learning.py
  mlfinlab/tests/test_symmetric_correlation_driven_nonparametric_learning_k.py
  mlfinlab/tests/test_universal_portfolio.py
Labels: enhancement

#316 [READY TO MERGE] Fix bisection method for HCAA
  mlfinlab/portfolio_optimization/hcaa.py
  mlfinlab/tests/test_hcaa.py
Labels: Portfolio Optimisation, bug

#309 [READY TO MERGE] Add custom objective function to Mean Variance
  mlfinlab/portfolio_optimization/hrp.py
  mlfinlab/portfolio_optimization/mean_variance.py
  mlfinlab/portfolio_optimization/risk_metrics.py
  mlfinlab/tests/test_mean_variance.py
Labels: Portfolio Optimisation, enhancement

#325 [READY TO MERGE] Fix research repo links
  docs/source/implementations/EF3M.rst
  docs/source/implementations/backtest_statistics.rst
  docs/source/implementations/backtesting.rst
  docs/source/implementations/bet_sizing.rst
  docs/source/implementations/cross_validation.rst
  docs/source/implementations/data_structures.rst
  docs/source/implementations/feature_clusters.rst
  docs/source/implementations/feature_importance.rst
  docs/source/implementations/frac_diff.rst
  docs/source/implementations/labeling_tail_sets.rst
  docs/source/implementations/sampling.rst
  docs/source/implementations/tb_meta_labeling.rst
  docs/source/portfolio_optimisation/critical_line_algorithm.rst
  docs/source/portfolio_optimisation/hierarchical_risk_parity.rst
  docs/source/portfolio_optimisation/mean_variance.rst
  docs/source/portfolio_optimisation/nested_clustered_optimisation.rst
  docs/source/portfolio_optimisation/risk_estimators.rst
  docs/source/portfolio_optimisation/theory_implied_correlation.rst
Labels: Documentation

#333 Do not let optimal number of clusters exceed max depth of tree
  mlfinlab/portfolio_optimization/hcaa.py
  mlfinlab/tests/test_data/stock_prices_2.csv
Labels: Portfolio Optimisation, bug

#330 [READY TO MERGE] Improve Portfolio Optimisation Documentation (Part-1)
  docs/source/portfolio_optimisation/hierarchical_clustering_asset_allocation.rst
  docs/source/portfolio_optimisation/hierarchical_risk_parity.rst
  docs/source/portfolio_optimisation/portfolio_optimisation_images/bisection.png
  docs/source/portfolio_optimisation/portfolio_optimisation_images/gap.png
  docs/source/portfolio_optimisation/portfolio_optimisation_images/seriation.png
Labels: Documentation, Portfolio Optimisation

#327 Labeling fixed time
  docs/source/implementations/labeling_fixed_time_horizon.rst
  docs/source/implementations/labeling_images/fixed_horizon_labels_example.png
  docs/source/index.rst
  mlfinlab/labeling/__init__.py
  mlfinlab/labeling/fixed_time_horizon.py
  mlfinlab/tests/test_labeling_fixed_time_horizon.py
Labels: Documentation, enhancement
