Repository hudson-and-thames/mlfinlab, pull requests merged in 2020-04, with the labels that each got.

#247 NCO, MCOS and De-noising module
  docs/source/implementations/portfolio_optimisation.rst
  mlfinlab/portfolio_optimization/__init__.py
  mlfinlab/portfolio_optimization/nco.py
  mlfinlab/portfolio_optimization/risk_estimators.py
  mlfinlab/tests/test_nco.py
  mlfinlab/tests/test_risk_estimators.py
Labels: Documentation, enhancement

#254 NCO docs fix
  docs/source/implementations/portfolio_optimisation.rst
  mlfinlab/portfolio_optimization/nco.py
Labels: Documentation

#215 Trend scanning labels
  docs/source/implementations/labeling_images/trend_scanning_plot.png
  docs/source/implementations/labeling_trend_scanning.rst
  docs/source/index.rst
  mlfinlab/__init__.py
  mlfinlab/labeling/__init__.py
  mlfinlab/labeling/trend_scanning.py
  mlfinlab/tests/test_labels.py
  mlfinlab/tests/test_trend_scanning_labels.py
Labels: enhancement

#259 Covariance calculation functions added to RiskEstimators module
  docs/source/implementations/portfolio_optimisation.rst
  mlfinlab/portfolio_optimization/risk_estimators.py
  mlfinlab/tests/test_risk_estimators.py
Labels: Documentation, enhancement

#264 Docs improved
  LICENSE.txt
  docs/source/additional_information/contact.rst
  docs/source/additional_information/contributing.rst
  docs/source/additional_information/images/slack.png
  docs/source/additional_information/license.rst
  docs/source/getting_started/barriers_to_entry.rst
  docs/source/getting_started/installation.rst
  docs/source/getting_started/requirements.rst
  docs/source/getting_started/researcher.rst
  docs/source/implementations/EF3M.rst
  docs/source/implementations/backtest_statistics.rst
  docs/source/implementations/backtesting.rst
  docs/source/implementations/bet_sizing.rst
  docs/source/implementations/clustering.rst
  docs/source/implementations/codependence.rst
  docs/source/implementations/cross_validation.rst
  docs/source/implementations/data_structures.rst
  docs/source/implementations/feature_importance.rst
  docs/source/implementations/filters.rst
  docs/source/implementations/frac_diff.rst
  docs/source/implementations/frac_diff_graph.png
  docs/source/implementations/labeling_tail_sets.rst
  docs/source/implementations/labeling_trend_scanning.rst
  docs/source/implementations/microstructural_features.rst
  docs/source/implementations/onc.rst
  docs/source/implementations/portfolio_optimisation.rst
  docs/source/implementations/sampling.rst
  docs/source/implementations/sb_bagging.rst
  docs/source/implementations/structural_breaks.rst
  docs/source/implementations/tb_meta_labeling.rst
  docs/source/index.rst
  docs/source/portfolio_optimisation/critical_line_algorithm.rst
  docs/source/portfolio_optimisation/hierarchical_clustering_asset_allocation.rst
  docs/source/portfolio_optimisation/hierarchical_risk_parity.rst
  docs/source/portfolio_optimisation/mean_variance.rst
  docs/source/portfolio_optimisation/nested_clustered_optimisation.rst
  docs/source/portfolio_optimisation/portfolio_optimisation_images/dendrogram.png
  docs/source/portfolio_optimisation/portfolio_optimisation_images/efficient_frontier.png
  docs/source/portfolio_optimisation/returns_estimation.rst
  docs/source/portfolio_optimisation/risk_estimators.rst
  docs/source/portfolio_optimisation/risk_metrics.rst
  mlfinlab/backtest_statistics/statistics.py
  mlfinlab/features/fracdiff.py
  mlfinlab/filters/filters.py
  mlfinlab/labeling/labeling.py
  mlfinlab/labeling/trend_scanning.py
  mlfinlab/microstructural_features/second_generation.py
  mlfinlab/portfolio_optimization/cla.py
  mlfinlab/portfolio_optimization/mean_variance.py
  mlfinlab/structural_breaks/chow.py
  mlfinlab/structural_breaks/sadf.py
  mlfinlab/tests/test_structural_breaks.py
Labels: Documentation

#270 TIC module
  docs/source/index.rst
  docs/source/portfolio_optimisation/theory_implied_correlation.rst
  mlfinlab/portfolio_optimization/__init__.py
  mlfinlab/portfolio_optimization/tic.py
  mlfinlab/tests/test_data/classification_tree.csv
  mlfinlab/tests/test_tic.py
Labels: Documentation, enhancement

#275 Recipe test
  .readthedocs.yml
  docs/requirements.txt
  docs/source/conf.py
  docs/source/index.rst
  docs/source/recipes/Financial Data Structure.ipynb
Labels: Documentation

#282 Benchmarks
  mlfinlab/__init__.py
  mlfinlab/online_portfolio_selection/__init__.py
  mlfinlab/online_portfolio_selection/benchmarks/best_constant_rebalanced_portfolio.py
  mlfinlab/online_portfolio_selection/benchmarks/best_stock.py
  mlfinlab/online_portfolio_selection/benchmarks/buy_and_hold.py
  mlfinlab/online_portfolio_selection/benchmarks/constant_rebalanced_portfolio.py
  mlfinlab/online_portfolio_selection/online_portfolio_selection.py
  mlfinlab/tests/test_best_constant_rebalanced_portfolio.py
  mlfinlab/tests/test_best_stock.py
  mlfinlab/tests/test_buy_and_hold.py
  mlfinlab/tests/test_constant_rebalanced_portfolio.py
  mlfinlab/tests/test_online_portfolio_selection.py
Labels: enhancement

#283 Speedup for ef3m in bet sizing
  mlfinlab/bet_sizing/ef3m.py
  mlfinlab/tests/test_ef3m.py
Labels: enhancement

#286 Ef3m speed
  mlfinlab/bet_sizing/ef3m.py
  mlfinlab/tests/test_bet_sizing.py
  mlfinlab/tests/test_ef3m.py
Labels: enhancement

#284 Momentum
  mlfinlab/online_portfolio_selection/__init__.py
  mlfinlab/online_portfolio_selection/benchmarks/best_constant_rebalanced_portfolio.py
  mlfinlab/online_portfolio_selection/benchmarks/best_stock.py
  mlfinlab/online_portfolio_selection/benchmarks/buy_and_hold.py
  mlfinlab/online_portfolio_selection/benchmarks/constant_rebalanced_portfolio.py
  mlfinlab/online_portfolio_selection/momentum/__init__.py
  mlfinlab/online_portfolio_selection/momentum/exponential_gradient.py
  mlfinlab/online_portfolio_selection/momentum/follow_the_leader.py
  mlfinlab/online_portfolio_selection/momentum/follow_the_regularized_leader.py
  mlfinlab/tests/test_exponential_gradient.py
  mlfinlab/tests/test_follow_the_leader.py
  mlfinlab/tests/test_follow_the_regularized_leader.py
Labels: enhancement
