Repository hudson-and-thames/mlfinlab, pull requests merged in 2020-07, with the labels that each got.

#397 labeling over mean
  docs/source/implementations/labeling_excess_mean.rst
  docs/source/implementations/labeling_images/distribution_over_mean.png
  docs/source/index.rst
  mlfinlab/labeling/__init__.py
  mlfinlab/labeling/excess_over_mean.py
  mlfinlab/tests/test_labeling_over_mean.py
Labels: Documentation, enhancement

#406 Update tail sets and add unit tests
  docs/source/implementations/labeling_tail_sets.rst
  mlfinlab/labeling/tail_sets.py
  mlfinlab/tests/test_labeling_tail_sets.py
Labels: Documentation, enhancement

#412 Fix MlFinLab issues
  docs/source/implementations/data_structures.rst
  docs/source/implementations/onc.rst
  docs/source/index.rst
  docs/source/labeling/labeling_excess_mean.rst
  docs/source/labeling/labeling_excess_median.rst
  docs/source/labeling/labeling_fixed_time_horizon.rst
  docs/source/labeling/labeling_images/MSFT_Return_vs_Benchmark.png
  docs/source/labeling/labeling_images/Raw_returns_distribution.png
  docs/source/labeling/labeling_images/bull_flag_template.png
  docs/source/labeling/labeling_images/confusion_matrix.png
  docs/source/labeling/labeling_images/distribution_over_mean.png
  docs/source/labeling/labeling_images/distribution_over_median_monthly_forward.png
  docs/source/labeling/labeling_images/fixed_horizon_labels_example.png
  docs/source/labeling/labeling_images/matrix_templates.png
  docs/source/labeling/labeling_images/meta_labeling_architecture.png
  docs/source/labeling/labeling_images/msft_bull_flag40.png
  docs/source/labeling/labeling_images/performance_tail_sets.png
  docs/source/labeling/labeling_images/tail_sets_perf.png
  docs/source/labeling/labeling_images/trend_scanning_plot.png
  docs/source/labeling/labeling_images/triple_barrier.png
  docs/source/labeling/labeling_images/var_distribution.png
  docs/source/labeling/labeling_matrix_flags.rst
  docs/source/labeling/labeling_raw_return.rst
  docs/source/labeling/labeling_tail_sets.rst
  docs/source/labeling/labeling_trend_scanning.rst
  docs/source/labeling/labeling_vs_benchmark.rst
  docs/source/labeling/tb_meta_labeling.rst
  mlfinlab/clustering/onc.py
  mlfinlab/features/fracdiff.py
  mlfinlab/microstructural_features/entropy.py
Labels: Documentation, bug

#421 Feature clusters update
  mlfinlab/clustering/feature_clusters.py
  mlfinlab/clustering/onc.py
  mlfinlab/tests/test_feature_clusters.py
Labels: bug, enhancement

#426 Fix double de-noising bug
  docs/source/conf.py
  mlfinlab/portfolio_optimization/mean_variance.py
  mlfinlab/portfolio_optimization/risk_estimators.py
  mlfinlab/tests/test_mean_variance.py
  mlfinlab/tests/test_risk_estimators.py
  setup.cfg
Labels: bug

#422 Codependence module update
  docs/source/codependence/codependence_marti.rst
  docs/source/codependence/codependence_matrix.rst
  docs/source/codependence/correlation_based_metrics.rst
  docs/source/codependence/images/dependence_copulas.PNG
  docs/source/codependence/images/optimal_transport_distance.png
  docs/source/codependence/images/target_copulas.PNG
  docs/source/codependence/information_theory_metrics.rst
  docs/source/codependence/optimal_transport.rst
  docs/source/index.rst
  docs/source/portfolio_optimisation/hierarchical_equal_risk_contribution.rst
  mlfinlab/codependence/__init__.py
  mlfinlab/codependence/codependence_matrix.py
  mlfinlab/codependence/information.py
  mlfinlab/codependence/optimal_transport.py
  mlfinlab/tests/test_codependence.py
  requirements.txt
  setup.cfg
Labels: Documentation, enhancement

#429 Codependence docs small fix
  docs/source/codependence/images/dependence_copulas.PNG
  docs/source/codependence/images/dependence_copulas.png
  docs/source/codependence/images/target_copulas.PNG
  docs/source/codependence/images/target_copulas.png
  docs/source/codependence/optimal_transport.rst
  docs/source/implementations/feature_clusters.rst
  docs/source/implementations/onc.rst
  docs/source/labeling/labeling_excess_mean.rst
  docs/source/labeling/labeling_excess_median.rst
  docs/source/labeling/labeling_fixed_time_horizon.rst
  docs/source/labeling/labeling_matrix_flags.rst
  docs/source/labeling/labeling_raw_return.rst
  docs/source/labeling/labeling_tail_sets.rst
  docs/source/labeling/labeling_vs_benchmark.rst
  docs/source/portfolio_optimisation/hierarchical_risk_parity.rst
Labels: Documentation
