Repository hudson-and-thames/mlfinlab, pull requests merged in 2020-02, with the labels that each got.

#172 Model Fingerpints algorithm
  docs/source/implementations/feature_imp_images/effects.png
  docs/source/implementations/feature_importance.rst
  mlfinlab/feature_importance/__init__.py
  mlfinlab/feature_importance/fingerpint.py
  mlfinlab/tests/test_fingerpint.py
Labels: enhancement

#165 Add Efficient Frontier Optimisation methods
  build/lib/mlfinlab/portfolio_optimization/returns_estimators.py
  build/lib/mlfinlab/portfolio_optimization/risk_estimators.py
  docs/source/implementations/portfolio_optimisation.rst
  docs/source/implementations/portfolio_optimisation_images/dendrogram.png
  docs/source/implementations/portfolio_optimisation_images/efficient_frontier.png
  mlfinlab/portfolio_optimization/cla.py
  mlfinlab/portfolio_optimization/hrp.py
  mlfinlab/portfolio_optimization/mean_variance.py
  mlfinlab/portfolio_optimization/returns_estimators.py
  mlfinlab/tests/test_portfolio_optimisation.py
  requirements.txt
Labels: enhancement

#192 Develop
  build/lib/mlfinlab/portfolio_optimization/returns_estimators.py
  build/lib/mlfinlab/portfolio_optimization/risk_estimators.py
  docs/source/implementations/portfolio_optimisation.rst
  docs/source/implementations/portfolio_optimisation_images/dendrogram.png
  docs/source/implementations/portfolio_optimisation_images/efficient_frontier.png
  mlfinlab/portfolio_optimization/cla.py
  mlfinlab/portfolio_optimization/hrp.py
  mlfinlab/portfolio_optimization/mean_variance.py
  mlfinlab/portfolio_optimization/returns_estimators.py
  mlfinlab/tests/test_portfolio_optimisation.py
  requirements.txt
Labels: enhancement

#202 Feature importance docs
  docs/source/implementations/feature_importance.rst
  mlfinlab/feature_importance/__init__.py
  mlfinlab/feature_importance/importance.py
  mlfinlab/feature_importance/orthogonal.py
  mlfinlab/tests/test_feature_importance.py
Labels: Documentation

#187 Moves package setup to setup.cfg file. Adds install_requires definition.
  setup.cfg
  setup.py
Labels: enhancement

#204 Develop
  docs/source/conf.py
  docs/source/implementations/feature_importance.rst
  mlfinlab/feature_importance/__init__.py
  mlfinlab/feature_importance/importance.py
  mlfinlab/feature_importance/orthogonal.py
  mlfinlab/tests/test_feature_importance.py
  setup.cfg
  setup.py
Labels: Documentation, bug

#143 Alternative input/output formats
  docs/source/implementations/data_structures.rst
  mlfinlab/data_structures/base_bars.py
  mlfinlab/data_structures/imbalance_data_structures.py
  mlfinlab/data_structures/run_data_structures.py
  mlfinlab/data_structures/standard_data_structures.py
  mlfinlab/data_structures/time_data_structures.py
  mlfinlab/tests/test_imbalance_data_structures.py
  mlfinlab/tests/test_standard_data_structures.py
Labels: enhancement
