Repository hudson-and-thames/mlfinlab, pull requests merged in 2020-01, with the labels that each got.

#155 Data structures/alex
  docs/source/implementations/data_structures.rst
  mlfinlab/data_structures/__init__.py
  mlfinlab/data_structures/base_bars.py
  mlfinlab/data_structures/imbalance_data_structures.py
  mlfinlab/data_structures/run_data_structures.py
  mlfinlab/data_structures/standard_data_structures.py
  mlfinlab/data_structures/time_data_structures.py
  mlfinlab/tests/test_imbalance_data_structures.py
  mlfinlab/tests/test_run_data_structures.py
  mlfinlab/tests/test_standard_data_structures.py
  mlfinlab/tests/test_time_data_structures.py
Labels: enhancement

#141 Add custom function to cross-validation/feat importance instead of str
  mlfinlab/cross_validation/cross_validation.py
  mlfinlab/feature_importance/importance.py
  mlfinlab/tests/test_cross_validation.py
  mlfinlab/tests/test_feature_importance.py
Labels: enhancement

#162 Add portfolio_optimisation module import in __init__
  README.md
  mlfinlab/__init__.py
Labels: bug

#167 Bug fixes
  docs/source/implementations/feature_importance.rst
  mlfinlab/__init__.py
  mlfinlab/feature_importance/orthogonal.py
  mlfinlab/filters/__init__.py
Labels: bug

#148 Microstructural features
  docs/source/implementations/microstructural_features.rst
  docs/source/implementations/microstructural_features_images/kyle_lambda.png
  docs/source/index.rst
  mlfinlab/microstructural_features/__init__.py
  mlfinlab/microstructural_features/encoding.py
  mlfinlab/microstructural_features/entropy.py
  mlfinlab/microstructural_features/feature_generator.py
  mlfinlab/microstructural_features/first_generation.py
  mlfinlab/microstructural_features/misc.py
  mlfinlab/microstructural_features/second_generation.py
  mlfinlab/microstructural_features/third_generation.py
  mlfinlab/tests/test_feature_importance.py
  mlfinlab/tests/test_labels.py
  mlfinlab/tests/test_microstructural_features.py
  mlfinlab/tests/test_sample_weights.py
  mlfinlab/tests/test_sampling.py
  mlfinlab/tests/test_sb_bagging.py
  mlfinlab/tests/test_volatility_features.py
  mlfinlab/util/__init__.py
  mlfinlab/util/misc.py
  mlfinlab/util/utils.py
  mlfinlab/util/volatility.py
  mlfinlab/util/volume_classifier.py
Labels: enhancement

#145 fixing future warning
  mlfinlab/labeling/labeling.py
Labels: enhancement

#156 Structural breaks
  docs/source/implementations/structural_breaks.rst
  docs/source/implementations/structural_breaks_images/sadf.png
  docs/source/index.rst
  mlfinlab/__init__.py
  mlfinlab/structural_breaks/__init__.py
  mlfinlab/structural_breaks/chow.py
  mlfinlab/structural_breaks/cusum.py
  mlfinlab/structural_breaks/sadf.py
  mlfinlab/tests/test_structural_breaks.py
  mlfinlab/util/fast_ewma.py
Labels: enhancement

#149 Solve bug from datetime index with time zone
  mlfinlab/labeling/labeling.py
  mlfinlab/tests/test_labels.py
  mlfinlab/tests/test_sampling.py
  mlfinlab/util/volatility.py
Labels: bug

#168 Onc clustering
  docs/source/implementations/clustering.rst
  docs/source/index.rst
  mlfinlab/__init__.py
  mlfinlab/clustering/__init__.py
  mlfinlab/clustering/onc.py
  mlfinlab/tests/test_onc.py
Labels: enhancement

#169 Develop
  docs/source/implementations/clustering.rst
  docs/source/implementations/data_structures.rst
  docs/source/implementations/feature_importance.rst
  docs/source/implementations/microstructural_features.rst
  docs/source/implementations/microstructural_features_images/kyle_lambda.png
  docs/source/implementations/structural_breaks.rst
  docs/source/implementations/structural_breaks_images/sadf.png
  docs/source/index.rst
  mlfinlab/__init__.py
  mlfinlab/clustering/__init__.py
  mlfinlab/clustering/onc.py
  mlfinlab/cross_validation/cross_validation.py
  mlfinlab/data_structures/__init__.py
  mlfinlab/data_structures/base_bars.py
  mlfinlab/data_structures/imbalance_data_structures.py
  mlfinlab/data_structures/run_data_structures.py
  mlfinlab/data_structures/standard_data_structures.py
  mlfinlab/data_structures/time_data_structures.py
  mlfinlab/feature_importance/importance.py
  mlfinlab/feature_importance/orthogonal.py
  mlfinlab/filters/__init__.py
  mlfinlab/labeling/labeling.py
  mlfinlab/microstructural_features/__init__.py
  mlfinlab/microstructural_features/encoding.py
  mlfinlab/microstructural_features/entropy.py
  mlfinlab/microstructural_features/feature_generator.py
  mlfinlab/microstructural_features/first_generation.py
  mlfinlab/microstructural_features/misc.py
  mlfinlab/microstructural_features/second_generation.py
  mlfinlab/microstructural_features/third_generation.py
  mlfinlab/structural_breaks/__init__.py
  mlfinlab/structural_breaks/chow.py
  mlfinlab/structural_breaks/cusum.py
  mlfinlab/structural_breaks/sadf.py
  mlfinlab/tests/test_cross_validation.py
  mlfinlab/tests/test_feature_importance.py
  mlfinlab/tests/test_imbalance_data_structures.py
  mlfinlab/tests/test_labels.py
  mlfinlab/tests/test_microstructural_features.py
  mlfinlab/tests/test_onc.py
  mlfinlab/tests/test_run_data_structures.py
  mlfinlab/tests/test_sample_weights.py
  mlfinlab/tests/test_sampling.py
  mlfinlab/tests/test_sb_bagging.py
  mlfinlab/tests/test_standard_data_structures.py
  mlfinlab/tests/test_structural_breaks.py
  mlfinlab/tests/test_time_data_structures.py
  mlfinlab/tests/test_volatility_features.py
  mlfinlab/util/__init__.py
  mlfinlab/util/fast_ewma.py
  mlfinlab/util/misc.py
  mlfinlab/util/utils.py
  mlfinlab/util/volatility.py
  mlfinlab/util/volume_classifier.py
Labels: Documentation, enhancement

#175 Codependence
  docs/source/conf.py
  docs/source/implementations/codependence.rst
  docs/source/implementations/codependence_images/abs.png
  docs/source/implementations/codependence_images/independent.png
  docs/source/implementations/codependence_images/linear.png
  docs/source/implementations/codependence_images/squared.png
  docs/source/index.rst
  mlfinlab/codependence/__init__.py
  mlfinlab/codependence/correlation.py
  mlfinlab/codependence/information.py
  mlfinlab/tests/test_codependence.py
Labels: enhancement

#176 Time bars issue
  mlfinlab/data_structures/base_bars.py
  mlfinlab/data_structures/time_data_structures.py
  mlfinlab/tests/test_data/tick_data_time_bars.csv
  mlfinlab/tests/test_time_data_structures.py
Labels: bug
