Repository hudson-and-thames/mlfinlab, pull requests merged in 2020-06, with the labels that each got.

#354 Improve Portfolio Optimisation Documentation (Part-2)
  docs/source/portfolio_optimisation/critical_line_algorithm.rst
  docs/source/portfolio_optimisation/hierarchical_clustering_asset_allocation.rst
  docs/source/portfolio_optimisation/hierarchical_risk_parity.rst
  docs/source/portfolio_optimisation/mean_variance.rst
  docs/source/portfolio_optimisation/nested_clustered_optimisation.rst
  docs/source/portfolio_optimisation/portfolio_optimisation_images/efficient_frontier.png
  docs/source/portfolio_optimisation/returns_estimation.rst
  docs/source/portfolio_optimisation/risk_estimators.rst
  docs/source/portfolio_optimisation/risk_metrics.rst
  docs/source/portfolio_optimisation/theory_implied_correlation.rst
  mlfinlab/portfolio_optimization/__init__.py
  mlfinlab/portfolio_optimization/cla.py
  mlfinlab/portfolio_optimization/hcaa.py
  mlfinlab/portfolio_optimization/hrp.py
  mlfinlab/portfolio_optimization/mean_variance.py
  mlfinlab/portfolio_optimization/returns_estimators.py
  mlfinlab/portfolio_optimization/risk_estimators.py
  mlfinlab/portfolio_optimization/tic.py
  mlfinlab/tests/test_cla.py
  mlfinlab/tests/test_hcaa.py
  mlfinlab/tests/test_hrp.py
  mlfinlab/tests/test_mean_variance.py
  mlfinlab/tests/test_risk_estimators.py
  mlfinlab/tests/test_tic.py
  requirements.txt
Labels: Documentation, Portfolio Optimisation

#362 Update risk_metrics.rst
  docs/source/portfolio_optimisation/risk_metrics.rst
Labels: Documentation

#380 Plot clusters in HCAA method
  docs/source/portfolio_optimisation/hierarchical_clustering_asset_allocation.rst
  docs/source/portfolio_optimisation/hierarchical_risk_parity.rst
  docs/source/portfolio_optimisation/portfolio_optimisation_images/dendrogram_hcaa.png
  mlfinlab/portfolio_optimization/hcaa.py
  mlfinlab/portfolio_optimization/hrp.py
  mlfinlab/tests/test_hcaa.py
  mlfinlab/tests/test_hrp.py
Labels: Portfolio Optimisation, enhancement

#337 Codependence by Marti / Codependence toctree / Bug fixes
  docs/source/codependence/codependence_marti.rst
  docs/source/codependence/codependence_matrix.rst
  docs/source/codependence/correlation_based_metrics.rst
  docs/source/codependence/images/abs.png
  docs/source/codependence/images/angular_distance.png
  docs/source/codependence/images/distance_correlation.png
  docs/source/codependence/images/entropy_relation_diagram.png
  docs/source/codependence/images/independent.png
  docs/source/codependence/images/linear.png
  docs/source/codependence/images/modified_angular_distance.png
  docs/source/codependence/images/squared.png
  docs/source/codependence/information_theory_metrics.rst
  docs/source/codependence/introduction.rst
  docs/source/implementations/codependence.rst
  docs/source/implementations/onc.rst
  docs/source/index.rst
  docs/source/portfolio_optimisation/risk_metrics.rst
  mlfinlab/codependence/__init__.py
  mlfinlab/codependence/codependence_matrix.py
  mlfinlab/codependence/correlation.py
  mlfinlab/codependence/gnpr_distance.py
  mlfinlab/codependence/information.py
  mlfinlab/labeling/labeling.py
  mlfinlab/tests/test_codependence.py
Labels: Documentation, enhancement

#384 stationarity + cointegration + regression
  docs/source/implementations/statistical_arbitrage.rst
  docs/source/implementations/statistical_arbitrage_images/all_regression.png
  docs/source/implementations/statistical_arbitrage_images/rolling_regression.png
  docs/source/implementations/statistical_arbitrage_images/stationary.png
  docs/source/implementations/statistical_arbitrage_images/trend_stationary.png
  docs/source/index.rst
  mlfinlab/__init__.py
  mlfinlab/statistical_arbitrage/__init__.py
  mlfinlab/statistical_arbitrage/cointegration.py
  mlfinlab/statistical_arbitrage/filtering.py
  mlfinlab/statistical_arbitrage/regression.py
  mlfinlab/statistical_arbitrage/stationarity.py
  mlfinlab/tests/test_cointegration.py
  mlfinlab/tests/test_regression.py
  mlfinlab/tests/test_stationarity.py
Labels: enhancement

#366 Labeling vs benchmark
  docs/source/implementations/labeling_images/MSFT_Return_vs_Benchmark.png
  docs/source/implementations/labeling_vs_benchmark.rst
  docs/source/index.rst
  mlfinlab/labeling/__init__.py
  mlfinlab/labeling/return_vs_benchmark.py
  mlfinlab/tests/test_labeling_vs_benchmark.py
Labels: Documentation, enhancement

#381 Update fth
  docs/source/implementations/labeling_fixed_time_horizon.rst
  mlfinlab/labeling/fixed_time_horizon.py
  mlfinlab/tests/test_labeling_fixed_time_horizon.py
Labels: bug, enhancement

#351 Labeling raw returns
  docs/source/implementations/labeling_images/Raw_returns_distribution.png
  docs/source/implementations/labeling_raw_return.rst
  docs/source/index.rst
  mlfinlab/labeling/__init__.py
  mlfinlab/labeling/raw_return.py
  mlfinlab/tests/test_labeling_raw_return.py
Labels: Documentation, enhancement

#342 Labeling excess median
  docs/source/implementations/labeling_excess_median.rst
  docs/source/implementations/labeling_images/distribution_over_median_monthly_forward.png
  docs/source/index.rst
  mlfinlab/labeling/__init__.py
  mlfinlab/labeling/excess_over_median.py
  mlfinlab/tests/test_labeling_over_median.py
Labels: Documentation, enhancement

#383 MlFinLab packages versions update
  .coveragerc
  .pylintrc
  .travis.yml
  coverage
  docs/source/getting_started/datasets.rst
  docs/source/implementations/backtesting.rst
  docs/source/implementations/feature_clusters.rst
  docs/source/implementations/feature_importance.rst
  docs/source/portfolio_optimisation/critical_line_algorithm.rst
  docs/source/portfolio_optimisation/hierarchical_clustering_asset_allocation.rst
  docs/source/portfolio_optimisation/hierarchical_risk_parity.rst
  docs/source/portfolio_optimisation/mean_variance.rst
  mlfinlab/bet_sizing/ch10_snippets.py
  mlfinlab/clustering/onc.py
  mlfinlab/cross_validation/cross_validation.py
  mlfinlab/data_structures/base_bars.py
  mlfinlab/ensemble/sb_bagging.py
  mlfinlab/feature_importance/importance.py
  mlfinlab/features/fracdiff.py
  mlfinlab/labeling/labeling.py
  mlfinlab/labeling/trend_scanning.py
  mlfinlab/microstructural_features/entropy.py
  mlfinlab/microstructural_features/second_generation.py
  mlfinlab/multi_product/etf_trick.py
  mlfinlab/online_portfolio_selection/base.py
  mlfinlab/portfolio_optimization/mean_variance.py
  mlfinlab/portfolio_optimization/nco.py
  mlfinlab/portfolio_optimization/tic.py
  mlfinlab/sample_weights/attribution.py
  mlfinlab/sampling/bootstrapping.py
  mlfinlab/sampling/concurrent.py
  mlfinlab/structural_breaks/chow.py
  mlfinlab/structural_breaks/cusum.py
  mlfinlab/structural_breaks/sadf.py
  mlfinlab/tests/test_backtests.py
  mlfinlab/tests/test_bet_sizing.py
  mlfinlab/tests/test_ch10_snippets.py
  mlfinlab/tests/test_data/imbalance_sample_data_small.csv
  mlfinlab/tests/test_feature_importance.py
  mlfinlab/tests/test_fingerpint.py
  mlfinlab/tests/test_imbalance_data_structures.py
  mlfinlab/tests/test_labels.py
  mlfinlab/tests/test_microstructural_features.py
  mlfinlab/tests/test_nco.py
  mlfinlab/tests/test_run_data_structures.py
  mlfinlab/tests/test_sample_weights.py
  mlfinlab/tests/test_sampling.py
  mlfinlab/tests/test_sb_bagging.py
  mlfinlab/tests/test_standard_data_structures.py
  mlfinlab/tests/test_structural_breaks.py
  mlfinlab/tests/test_time_data_structures.py
  mlfinlab/util/multiprocess.py
  mlfinlab/util/volume_classifier.py
  requirements.txt
  scripts/run_tests.py
  setup.cfg
Labels: CI, enhancement

#391 Research Tools Docs
  docs/source/getting_started/getting_started_images/derivative.png
  docs/source/getting_started/getting_started_images/graph.png
  docs/source/getting_started/getting_started_images/prior.png
  docs/source/getting_started/research_tools.rst
  docs/source/index.rst
Labels: Documentation

#389 Denoising and detoning to RiskEstimators
  docs/source/portfolio_optimisation/risk_estimators.rst
  mlfinlab/portfolio_optimization/risk_estimators.py
  mlfinlab/tests/test_risk_estimators.py
Labels: Documentation, enhancement

#399 Change HCAA to HERC
  docs/source/index.rst
  docs/source/portfolio_optimisation/hierarchical_equal_risk_contribution.rst
  docs/source/portfolio_optimisation/hierarchical_risk_parity.rst
  docs/source/portfolio_optimisation/portfolio_optimisation_images/dendrogram_hcaa.png
  docs/source/portfolio_optimisation/portfolio_optimisation_images/dendrogram_herc.png
  mlfinlab/portfolio_optimization/__init__.py
  mlfinlab/portfolio_optimization/herc.py
  mlfinlab/portfolio_optimization/tic.py
  mlfinlab/tests/test_herc.py
Labels: Documentation

#398 Fixed #394
  docs/source/online_portfolio_selection/benchmarks.rst
  docs/source/online_portfolio_selection/introduction.rst
  docs/source/online_portfolio_selection/mean_reversion.rst
  docs/source/online_portfolio_selection/momentum.rst
  docs/source/online_portfolio_selection/pattern_matching.rst
  docs/source/online_portfolio_selection/universal_portfolio.rst
Labels: Documentation

#402 [Draft] Fix MlFinLab issues
  docs/source/implementations/data_structures.rst
  docs/source/implementations/feature_importance.rst
  docs/source/implementations/frac_diff.rst
  docs/source/implementations/labeling_tail_sets.rst
  docs/source/implementations/plot_min_ffd_graph.png
  docs/source/implementations/sb_bagging.rst
  mlfinlab/backtest_statistics/statistics.py
  mlfinlab/data_structures/standard_data_structures.py
  mlfinlab/feature_importance/orthogonal.py
  mlfinlab/features/__init__.py
  mlfinlab/features/fracdiff.py
  mlfinlab/sampling/bootstrapping.py
  mlfinlab/tests/test_backtest_statistics.py
  mlfinlab/tests/test_feature_importance.py
  mlfinlab/tests/test_fracdiff.py
  mlfinlab/tests/test_standard_data_structures.py
  requirements.txt
Labels: CI, Documentation, bug, enhancement

#410 Labeling matrix flags
  docs/source/implementations/labeling_images/bull_flag_template.png
  docs/source/implementations/labeling_images/matrix_templates.png
  docs/source/implementations/labeling_images/msft_bull_flag40.png
  docs/source/implementations/labeling_matrix_flags.rst
  docs/source/index.rst
  mlfinlab/labeling/__init__.py
  mlfinlab/labeling/matrix_flags.py
  mlfinlab/tests/test_labeling_matrix_flags.py
Labels: Documentation, enhancement

#409 Notes for OLPS module
  docs/source/online_portfolio_selection/introduction.rst
Labels: Documentation
